### ISSUE TITLE
Allow header configuration

### ISSUE THREAD

**Issue by brianfoody** [seglo/connect-prism#13]
Created as per comment https://github.com/seglo/connect-prism/pull/9#issuecomment-53410420

The current configuration only plucks certain headers (content-encoding, content-type and location from what I can see).

I think it would be better to allow the user to control this. Perhaps something like I'm doing for issue #8 where we have a headers field and;
false // don't record any
true // record all
array // only record these / only exclude these

Or else you could just record all headers.

**Comment by seglo** [comment]
Thanks!
