### ISSUE TITLE
Consequent requests

### ISSUE THREAD

**Issue by dmitrytrager** [seglo/connect-prism#27]
Need an ability to distinguish consequent requests within one tests.
Now it's recorded into one mock, because url and query string are the same.

**Comment by ziprandom** [comment]
i implemented this feature within my fork. it´s not documented atm. but you should be able to understand it when you look at the integration tests ... basically it records the mock file names with a sequence number ...

**Comment by seglo** [comment]
Issue cleanup.  Re-open if you'd like to contribute.
