### ISSUE TITLE
Act as a true web proxy

### ISSUE THREAD

**Issue by dlecan** [seglo/connect-prism#28]
As connect-prism features are pretty good, I would like to use connect-prism to setup a true web proxy for my Karma tests. Actually, connect-prism is more a kind of reverse-proxy than a proxy.

My requirement ? "target url" should be read from the client request instead of being hard written in Gruntfile.

**Comment by seglo** [comment]
I think this would extend the scope of prism too much, sorry.  I believe there are other projects that could satisfy this request.
