### ISSUE TITLE
Proxying to proxy

### ISSUE THREAD

**Issue by dlecan** [seglo/connect-prism#29]
It would be great if connect-prism could forward received requests to another proxy.

Use case: to work with a webapi behind a proxy with authentication

Maybe this can be achieved with [toProxy](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy.js#L40) option from node-http-proxy ? (see https://github.com/nodejitsu/node-http-proxy#options too)

**Comment by CatBakun** [comment]
@dlecan Id like to do the same, have you resolve the situation?

Thanks

**Comment by seglo** [comment]
I'm going to take a look into this after I release `1.0.0` (in the next few days), but feel free to submit a PR in the mean time if you want to have a hand at implementing it.
