### ISSUE TITLE
Set StatusCode through URL

### ISSUE THREAD

**Issue by jlnslv** [seglo/connect-prism#34]
Hi there,

Is there a way to get a different response from the same URL? 

For example: I've got /api/login and I want to get a 200 for a successful login and a 401 when login failed.

Thanks for your help.

Regards,
Julien

**Comment by seglo** [comment]
Hi @jlnslv. Yes you can achieve this functionality by using the API.  See the following FAQ entry for more details.

[How do I programmatically configure prism in my testsuite and override mocks?](https://github.com/seglo/connect-prism/wiki#how-do-i-programmatically-configure-prism-in-my-testsuite-and-override-mocks)
