### ISSUE TITLE
Extra mock files created using humanReadable + ignoreParameters

### ISSUE THREAD

**Issue by meyerds** [seglo/connect-prism#40]
I'm using the ignoreParameters option and setting the mock filename to be humanReadable.

I expected to see one file created after submitting two requests where the only difference between requests is the value of an ignored parameter. That wasn't the case, instead the filename is generated with the parameters included and so two mock files are created.

A brief look at the source code made me think mock-filename-generator.js:34 should use a prismUtils.filteredUrl() instead of the URL right out of the request?

Thanks!

**Comment by seglo** [comment]
Thanks for reporting this.  Apologies for the super late response.
