### ISSUE TITLE
Grunt is a full dependency, not a devDependency

### ISSUE THREAD

**Issue by jj4th** [seglo/connect-prism#42]
You still require grunt in `lib/prism.js` and use it for limited file handling elsewhere in the file.  In a project that does not use grunt, this causes an error:

```
Error: Cannot find module 'grunt'
...  at Object.<anonymous> (node_modules/connect-prism/lib/prism.js:8:13)
```

**Comment by seglo** [comment]
Oops.  Thanks for letting me know.
