### ISSUE TITLE
Wrong dependency for di selected

### ISSUE THREAD

**Issue by csabakoncz** [seglo/connect-prism#43]
Hi,

In version 1.0.5 the di dependency was changed from "2.0.0-pre-14" to "^2.0.0-pre-14"
(https://github.com/seglo/connect-prism/commit/0192cda801ac80f87ccb5bab61f3da2cf02fd9f8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R46)
What was the intent of the change? Right now, there is no newer di version and on my system, di@2.0.0-pre-9 is selected.

```
1265 silly addNameRange number 2 { name: 'di', range: '>=2.0.0-pre-14 <3.0.0', hasData: true }
1266 silly addNameRange versions [ 'di',
1266 silly addNameRange   [ '0.0.0',
1266 silly addNameRange     '0.0.1',
1266 silly addNameRange     '1.9.0',
1266 silly addNameRange     '2.0.0-pre-1',
1266 silly addNameRange     '2.0.0-pre-2',
1266 silly addNameRange     '2.0.0-pre-3',
1266 silly addNameRange     '2.0.0-pre-4',
1266 silly addNameRange     '2.0.0-pre-5',
1266 silly addNameRange     '2.0.0-pre-6',
1266 silly addNameRange     '2.0.0-pre-7',
1266 silly addNameRange     '2.0.0-pre-8',
1266 silly addNameRange     '2.0.0-pre-9',
1266 silly addNameRange     '2.0.0-pre-10',
1266 silly addNameRange     '2.0.0-pre-11',
1266 silly addNameRange     '2.0.0-pre-12',
1266 silly addNameRange     '2.0.0-pre-13',
1266 silly addNameRange     '2.0.0-pre-14' ] ]
1267 silly addNamed di@2.0.0-pre-9
1268 verbose addNamed "2.0.0-pre-9" is a plain semver version for di
1269 silly mapToRegistry name di
1270 silly mapToRegistry using default registry
1271 silly mapToRegistry registry https://registry.npmjs.org/
1272 silly mapToRegistry uri https://registry.npmjs.org/di
1273 verbose addRemoteTarball https://registry.npmjs.org/di/-/di-2.0.0-pre-9.tgz not in flight; adding
1274 verbose addRemoteTarball [ 'https://registry.npmjs.org/di/-/di-2.0.0-pre-9.tgz',
1274 verbose addRemoteTarball   'b51fb4c3a7a1cb231396e1abce4f0ecfe187b6df' ]
```

The bad thing is that this version fails to install due to its dependency on "traceur" specified as "vojtajina/traceur-compiler#add-es6-pure-transformer-dist".

So right now I can do an "npm install connect-prism@1.0.3" but not "npm install connect-prism@1.0.5".

**Comment by csabakoncz** [comment]
Sorry, found it out only now that the issue occurs only on Windows. 
On Linux I can install connect-prism@1.0.5. 

On windows I can not even run an "npm pack", so I have to check that first.

**Comment by csabakoncz** [comment]
And on Windows, I only have problems when running npm from Git Bash. When using the Windows command shell, I can do "npm pack" and also install connect-prism@1.0.5

**Comment by seglo** [comment]
Oops.  Thank you.
