### ISSUE TITLE
Mock file names can get so long that they break Windows

### ISSUE THREAD

**Issue by sbaechler** [seglo/connect-prism#48]
When a request has mulitple query strings the human readable file names can get really long.

My colleagues who use Windows or Ubuntu (with directory encryption) are unable to checkout a branch that contains mocks with those long names. 

Maybe limit the length of the generated file names.

**Comment by seglo** [comment]
That sucks.  I would suggest having a shorter path (put your project somewhere closer to your drive root).  Or implementing your own `mockFilenameGenerator`.
