### ISSUE TITLE
connect-prism doesn't use existing mocks

### ISSUE THREAD

**Issue by noelmace** [seglo/connect-prism#51]
**Issue**

Connect-prism doesn't use previously committed (and renamed, for human readability) mock files. Of course, this files have been created on another computer, by another developer, in the same git project.

**Workaround**

For now, we have to : 
1. run connect-prim in mock, mockrecord or record mode in order to get the 404 files or a new recorded mock
2. if needed, remove the 404 extension, then replace the content of this mock with the one previously committed
3. ignore this new mocks in every commit after that

This workaround needs to be repeated every time a mock is created or modified.

**Context**

As I used BrowserSync in the first place, and wanted to use connect-prism, my gulp "serve" task create a BrowserSync server, proxying requests to the backend (thanks to http-proxy-middleware) to a connect server wich use connect-prism for mocking.

The mocks are stored in the mocks/ folder.

I use : 
- connect-prism 1.0.6
- browsersync ^2.12.5
- http-proxy-middleware ^0.17.1

You can find all the configuration in Sedona-Solutions/sdn-angularjs-seed ([gulp/tasks/serve.js](https://github.com/Sedona-Solutions/sdn-angularjs-seed/blob/master/gulp/tasks/serve.js))

**Comment by nweldev** [comment]
Sping cleaning 2019 :wink:

**Comment by seglo** [comment]
@noelmace Thanks ;) I don't do much work in node or web dev in general these days I'm afraid.
