### ISSUE TITLE
proxy is removing content-length from header

### ISSUE THREAD

**Issue by longstone** [seglo/connect-prism#52]
We're using prism to add a specific header field to requests. When loading files the `content-length` header field is removed which causes broken downloads. This happens only if `Content-disposition attachment;` is set.

This could be an issue with prism, because accessing the server directly via postman worked. When accessing via prism the `content-length` field was missing.

**Comment by seglo** [comment]
Can you confirm if this is still an issue in 1.0.12 after this fix: https://github.com/seglo/connect-prism/pull/47/commits/24fcbac78ba7894ed45cbfdb6530154884803c01
