### ISSUE TITLE
useapi() doesn't work after creating a prism server with the POST /_prism/create method 

### ISSUE THREAD

**Issue by KFMichael** [seglo/connect-prism#53]
i would like to use the useapi() feature. 
But when I enable it by using `prism.useApi()`  ( just after prim = require('connect-prism') , and after created a prism server ( with POST /_prism/create ),  i can't access to the API anymore. 

the prism server proxifies the request  ( like GET  http://myprismConnectserver:prismPort/_prism/version ), and response with a 404  .

am'i doing it in the wrong way ?

**Comment by seglo** [comment]
Were you able to sort this out?

**Comment by KFMichael** [comment]
Partially. I can create a new prism server. But when the prism is created ( in record mode), request like GET /_prism/version is proxify.

**Comment by seglo** [comment]
Can you paste your config?

**Comment by KFMichael** [comment]
--------------------------------------------------------------
var http = require('http');
var connect = require('connect');
var prism = require('connect-prism');

prism.useApi();
prism.useVerboseLog();

var app = connect()
    .use(prism.middleware);

http.createServer(app).listen(3000);
------------------------------------------------------
here is the way i use

**Comment by jtbonhomme** [comment]
I think the problem is that the context is set to "/".
Then, any call to an internal api route such as "/_prism" is considered as a request to be proxified.

**Comment by seglo** [comment]
@jtbonhomme is correct.  This is a common stumbling block and probably requires a mention in the docs.

**Comment by jtbonhomme** [comment]
@seglo do you think it could be easy to add a config rule that would only proxy request from a specified User-Agent for example ? So it could be easy to call '/_prism' with another User-Agent, so that the remove command would not be proxified ...?

**Comment by seglo** [comment]
@jtbonhomme maybe.  There's a feature shouldRecord that could be used for this purpose, while in record mode.  Perhaps something similar for the other modes would be useful.

**Comment by jtbonhomme** [comment]
Sean, I found a simple fix. If you switch in index.js the tests on HttpRequest and API, it works !
I made a PR #54 to propose this quick fix. Tests are OK. I also tested that you could still use /_prism/version after having created a proxy with context "/".
Let me know if it is OK to you !

**Comment by KFMichael** [comment]
#54 just fix it :) thanks
