### ISSUE TITLE
mock response file for request with query params

### ISSUE THREAD

**Issue by miestr** [seglo/connect-prism#64]
**Issue**
I try to mock a response for a HTTP GET with two query parameters. When prism tries to create a serialized response file, the "&" between query parameters is replaced with "?", but Windows 10 does not allow to create files with this character. So prism can not create the file and thus can't mock the response.

**Code**:
`let params = { params: { lang: 'en', type: 'car' } };`
`return this.$http.get("service/vehicles", params).then(res => res.data);`

**Error:**
`info: Serialized empty 404 response for /service/vehicles?lang=en&type=car to mocks\serve\service\_service_vehicles_lang=en?type=car_8002ccd3109ba61c96894a5a5f04b68e0636b73a.json.404
fs.js:60`
      `throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs`
      `^`

`Error: ENOENT: no such file or directory, open '...path....\mocks\serve\service\_service_vehicles_lang=en?type=car_8002ccd3109ba61c96894a5a5f04b68e0636b73a.json.404'
    at Error (native)`

I already tried to create the file manually, with "&" between the params, but prism does not see it. 
Is there any solution?
Any help is highly appreciated.

**Comment by KFMichael** [comment]
May be you can use the prism option : mockFilenameGenerator for creating a special function in which you can escape/replace the '?'  ...

**Comment by miestr** [comment]
Thank you for the reply! I think the bug is fixed with merge request #66 by brunnurs.
