### ISSUE TITLE
ignoreParameters let prism crash on windows 

### ISSUE THREAD

**Issue by brunnurs** [seglo/connect-prism#67]
A small bug in the `MockFilenameGenerator` causes prism to crash under windows as soon as the URL to mock contains a question mark (so basically all requests with query parameters) and the `ignoreParameters` flag is used .

Reason: the sanitizing of the url is done before the filtering for ignored parameters:

```javascript
var url = prismUtils.filterUrl(config, req.url.replace(/\/|\_|\?|\<|\>|\\|\:|\*|\||\"/g,'_'));
```

But in the filter-method, the question-mark is added again:

```javascript
if (!_.isEmpty(filteredParameters)) {
  urlPath += "?" + filteredParameters.join("&");
}
```

As the question mark is forbidden in windows file names, prism crashes the hard way when it tries to create the file.

Another side effect of this bug is that the first parameter will never be ignored, as after the sanitizing it is seen as part of the base-URL by the `filterUrl() ` method 

In my opinion the expected result in test

```javascript
it('should support a human readable filename generator function and support ignoreParameters configuration', function() {
```

is currently not correct. With  `ignoreParameters = true ` all parameters should get ignored.

This pull request  (https://github.com/seglo/connect-prism/pull/66) fixes the bug. I wrote a test for the question-mark issue and adapted the test mentioned above according to the specification in README.md.

**Comment by seglo** [comment]
Thanks @brunnurs .  I'll release this fix momentarily.
